[package]
name = "weldify/hylic"
description = "A Roblox framework to make code communication easier"
license = "MIT"
authors = ["Weldify"]
version = "0.19.3"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
